#!/bin/bash

# this script generates the nodetime binary for multiple platforms and moves 
# them to the Go source code, the pkg/nodetime pkg.

set -e

function cleanup () {
    rm -rf dist/ nodetime-*
}

cleanup

cd ./scripts/data/gen-nodetime

npm i

./node_modules/typescript/bin/tsc

./node_modules/pkg/lib-es5/bin.js \
    --debug \
    --no-bytecode --public-packages "*" --public \
    -t node14-linux-x64,node14-linux-arm64,node14-macos-x64 \
    -o nodetime \
    .

tar -czvf nodetime-linux-amd64.tar.gz nodetime-linux-x64
tar -czvf nodetime-linux-arm64.tar.gz nodetime-linux-arm64
tar -czvf nodetime-darwin-amd64.tar.gz nodetime-macos-x64

cp nodetime-*.tar.gz ../../../starport/pkg/nodetime/data

cleanup
